"""
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:

        if not s:
            return t
        
        #  store the length of the given two strings
        t_len = len(t)
        s_len = len(s)

        # s_char_freq_map 
        s_char_freq_map = {}

        #  iterate the s string
        for ch in s:
            #  store all it's characters in s_char_freq_map
            s_char_freq_map[ch] = s_char_freq_map.get(ch, 0) + 1

        #  iterate the t string
        for ch in t:
            #  check if character  of t at the current index is present in s_char_freq_map or not 
            #  Even if it is present sometimes, check it's frequency if it is 'zero'
            #  return that character, since it is the extra character
            if ch not in s_char_freq_map or s_char_freq_map[ch] == 0:
                return ch
            
            # decrement each time, to indicate that we traversed that character already
            s_char_freq_map[ch] -= 1
    

s = Solution()
print(s.findTheDifference("abcd", "abcde"))
print(s.findTheDifference("", "y"))
print(s.findTheDifference("ae", "aea"))