"""
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:

        if not s:
            return t
        
        #  sort the given two strings
        sorted_s = sorted(s)
        sorted_t = sorted(t)

        #  store the length of sorted_s
        s_len = len(sorted_s)
        # initialize a variables
        i = 0

        #  iterate any of the strings
        while i < s_len:
            #  check whether if characters at their respective indices are equal or not
            if sorted_s[i] != sorted_t[i]:
                # If not equal, return that particular character
                return sorted_t[i]
            
            i += 1
        
        #  return the last character
        return sorted_t[i]
    

s = Solution()
print(s.findTheDifference("abcd", "abcde"))
print(s.findTheDifference("", "y"))
print(s.findTheDifference("ae", "aea"))